### ISSUE TITLE
CSS missing after upgrading from version 6.19

### ISSUE THREAD

**Issue by atlasstrategic** [vega/vega-embed#792]
The latest version of vega-embed (>6.19) is missing CSS placed in header using `<style id=vega-embed-style>`:

```css
.vega-embed {
    position: relative;
    display: inline-block;
    box-sizing: border-box;
}
```
The missing CSS results in overlapping summary view-actions buttons (when rendering multiple charts on a HTML page).
